# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x11\n\x0fGetUsersRequest\"(\n\x10GetUsersResponse\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\"!\n\x13GetUsersByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x13GetUserByIdResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"(\n\x11\x43reateUserRequest\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\")\n\x12\x43reateUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"(\n\x11UpdateUserRequest\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\")\n\x12UpdateUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x12\x44\x65leteUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User2\xa2\x02\n\x05Users\x12\x31\n\x08GetUsers\x12\x10.GetUsersRequest\x1a\x11.GetUsersResponse\"\x00\x12;\n\x0bGetUserById\x12\x14.GetUsersByIdRequest\x1a\x14.GetUserByIdResponse\"\x00\x12\x37\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\"\x00\x12\x37\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\"\x00\x12\x37\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_GETUSERSREQUEST = DESCRIPTOR.message_types_by_name['GetUsersRequest']
_GETUSERSRESPONSE = DESCRIPTOR.message_types_by_name['GetUsersResponse']
_GETUSERSBYIDREQUEST = DESCRIPTOR.message_types_by_name['GetUsersByIdRequest']
_GETUSERBYIDRESPONSE = DESCRIPTOR.message_types_by_name['GetUserByIdResponse']
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_CREATEUSERRESPONSE = DESCRIPTOR.message_types_by_name['CreateUserResponse']
_UPDATEUSERREQUEST = DESCRIPTOR.message_types_by_name['UpdateUserRequest']
_UPDATEUSERRESPONSE = DESCRIPTOR.message_types_by_name['UpdateUserResponse']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteUserRequest']
_DELETEUSERRESPONSE = DESCRIPTOR.message_types_by_name['DeleteUserResponse']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

GetUsersRequest = _reflection.GeneratedProtocolMessageType('GetUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:GetUsersRequest)
  })
_sym_db.RegisterMessage(GetUsersRequest)

GetUsersResponse = _reflection.GeneratedProtocolMessageType('GetUsersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:GetUsersResponse)
  })
_sym_db.RegisterMessage(GetUsersResponse)

GetUsersByIdRequest = _reflection.GeneratedProtocolMessageType('GetUsersByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSBYIDREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:GetUsersByIdRequest)
  })
_sym_db.RegisterMessage(GetUsersByIdRequest)

GetUserByIdResponse = _reflection.GeneratedProtocolMessageType('GetUserByIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERBYIDRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:GetUserByIdResponse)
  })
_sym_db.RegisterMessage(GetUserByIdResponse)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

CreateUserResponse = _reflection.GeneratedProtocolMessageType('CreateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserResponse)
  })
_sym_db.RegisterMessage(CreateUserResponse)

UpdateUserRequest = _reflection.GeneratedProtocolMessageType('UpdateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserRequest)
  })
_sym_db.RegisterMessage(UpdateUserRequest)

UpdateUserResponse = _reflection.GeneratedProtocolMessageType('UpdateUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserResponse)
  })
_sym_db.RegisterMessage(UpdateUserResponse)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

DeleteUserResponse = _reflection.GeneratedProtocolMessageType('DeleteUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:DeleteUserResponse)
  })
_sym_db.RegisterMessage(DeleteUserResponse)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=15
  _USER._serialized_end=80
  _GETUSERSREQUEST._serialized_start=82
  _GETUSERSREQUEST._serialized_end=99
  _GETUSERSRESPONSE._serialized_start=101
  _GETUSERSRESPONSE._serialized_end=141
  _GETUSERSBYIDREQUEST._serialized_start=143
  _GETUSERSBYIDREQUEST._serialized_end=176
  _GETUSERBYIDRESPONSE._serialized_start=178
  _GETUSERBYIDRESPONSE._serialized_end=220
  _CREATEUSERREQUEST._serialized_start=222
  _CREATEUSERREQUEST._serialized_end=262
  _CREATEUSERRESPONSE._serialized_start=264
  _CREATEUSERRESPONSE._serialized_end=305
  _UPDATEUSERREQUEST._serialized_start=307
  _UPDATEUSERREQUEST._serialized_end=347
  _UPDATEUSERRESPONSE._serialized_start=349
  _UPDATEUSERRESPONSE._serialized_end=390
  _DELETEUSERREQUEST._serialized_start=392
  _DELETEUSERREQUEST._serialized_end=423
  _DELETEUSERRESPONSE._serialized_start=425
  _DELETEUSERRESPONSE._serialized_end=466
  _USERS._serialized_start=469
  _USERS._serialized_end=759
# @@protoc_insertion_point(module_scope)
